version: '3'
services:
  app:
    image: course-management-compose
    restart: always
    build : 
      dockerfile: dockerfile
      context: .
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysqldb
    command: npm run start:dev
    ports: 
      - "8080:3000"

  mysqldb:
   image: mysql:5.7
   restart: always
   ports:
      - 3306:3306
   environment:
     
       MYSQL_DATABASE: course-management
       MYSQL_USER: root
       MYSQL_ROOT_HOST: localhost
       MYSQL_ALLOW_EMPTY_PASSWORD: 
   volumes:
      - mysql_data:/var/lib/mysql 
  #keep our data alive after restart
volumes:
 mysql_data:
    name: mysql_data

 
 
 
 
 